### ISSUE TITLE
Headphone landing page .

### ISSUE THREAD

**Issue by Dimple-Choudhary** [GDSC-CEC/HacktoberFest-2022-Web-Development#46]

**Comment by Dimple-Choudhary** [comment]
Please assign me this issue

**Comment by Dimple-Choudhary** [comment]
Please @ChiragGupta2808  accept my Pull Request under hacktoberfest 2022

**Comment by snehasish-pathak** [comment]
**Can you assign this issue to me ?**

**Comment by ChiragGupta2808** [comment]
@Dimple-Choudhary accepted your PR.
